# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{big_money}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shane Hanna", "Marshall Roch"]
  s.date = %q{2010-01-22}
  s.email = ["shane.hanna@gmail.com", "mroch@cmu.edu"]
  s.executables = ["rubyforge", "edit_json.rb", "convert_to_should_syntax", "erubis", "jeweler", "prettify_json.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "big_money.gemspec",
     "lib/big_money.rb",
     "lib/big_money/currency.rb",
     "lib/big_money/currency/iso4217.rb",
     "lib/big_money/exchange.rb",
     "lib/big_money/exchange/yahoo.rb",
     "lib/big_money/ext.rb",
     "lib/big_money/parser.rb",
     "rakelib/iso4217.rb",
     "rakelib/iso4217.rb.erb",
     "test/helper.rb",
     "test/test_big_money.rb",
     "test/test_currency.rb",
     "test/test_exchange.rb",
     "test/test_parser.rb"
  ]
  s.homepage = %q{http://github.com/shanna/big_money}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{BigDecimal backed amount of money in a particular currency.}
  s.test_files = [
    "test/test_exchange.rb",
     "test/helper.rb",
     "test/test_currency.rb",
     "test/test_big_money.rb",
     "test/test_parser.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

