# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "big_money"
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shane Hanna", "Marshall Roch"]
  s.date = "2012-12-20"
  s.description = "BigDecimal backed amount of money in a particular currency."
  s.email = ["shane.hanna@gmail.com", "mroch@cmu.edu"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "big_money.gemspec",
    "lib/big_money.rb",
    "lib/big_money/currency.rb",
    "lib/big_money/currency/iso4217.rb",
    "lib/big_money/exchange.rb",
    "lib/big_money/exchange/yahoo.rb",
    "lib/big_money/parser.rb",
    "lib/big_money/types.rb",
    "rakelib/iso4217.rb",
    "rakelib/iso4217.rb.erb",
    "test/helper.rb",
    "test/test_big_money.rb",
    "test/test_currency.rb",
    "test/test_exchange.rb",
    "test/test_parser.rb"
  ]
  s.homepage = "http://github.com/shanna/big_money"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = nil

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<hpricot>, [">= 0"])
      s.add_development_dependency(%q<erubis>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0"])
      s.add_dependency(%q<erubis>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0"])
    s.add_dependency(%q<erubis>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

